version: 1.3.0
services:
  - mysql
  - composer:
      version: 2
  - php:
      version: 8.2

variables:
  global:
    COMPOSER_BIN: $SOURCE_DIR/vendor/bin
    BLT_DIR: $SOURCE_DIR/vendor/acquia/blt

events:
  build:
    steps:
        - setup-env:
            type: script
            script:
              # Set git info.
              - git config --global user.name "Acquia Cloud"
              - git config --global user.email "no-reply@example.com"
              # Create MySQL DB.
              - mysql -u root -proot -e "CREATE DATABASE IF NOT EXISTS drupal"
              - ldd --version
        - js:
            type: script
            script:
              # Acquia pipelines need to be updated to go higher than npm 10
              - cd docroot/themes/custom/twentynineteen
              - node --version
              - nvm use 20
              - node --version
              - npm install
        - dependencies:
            type: script
            script:
              - cd $SOURCE_DIR
              - composer install --ansi
        - validate:
            type: script
            script:
              - cd $SOURCE_DIR
              - composer run-validation
        - setup-app:
            type: script
            script:
              - cd $SOURCE_DIR
              - composer site-install
        - tests:
            type: script
            script:
              - source ${BLT_DIR}/scripts/pipelines/tests
        - build-artifact:
            type: script
            script:
              - cd $SOURCE_DIR
              - mkdir /tmp/acli-push-artifact
              - acli push:artifact --dry-run --no-clone --no-commit
              - mv .git /tmp/acli-push-artifact/
              - shopt -s dotglob && rm -rf ./* && mv /tmp/acli-push-artifact/* ./
